# -*- coding: utf-8 -*-
"""Agent2_emna

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qiKh10560-FtfnhrDEzsq7T2lFDgHZK9
"""

# ═══════════════════════════════════════════════════════════════════════════
# CELL 1: Dependencies
# ═══════════════════════════════════════════════════════════════════════════

import sys

# ═══════════════════════════════════════════════════════════════════════════
# CELL 2: Config & API Keys
# ═══════════════════════════════════════════════════════════════════════════

import os

import sys
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))
from config import GROQ_API_KEY, SERPAPI_KEY, APIFY_API_TOKEN

GROQ_MODEL  = "llama-3.3-70b-versatile"
OUTPUT_DIR  = "agent2_output"
os.makedirs(OUTPUT_DIR, exist_ok=True)

CHECKPOINT_FILE  = os.path.join(OUTPUT_DIR, "web_features.csv")
VALIDATION_LOG   = os.path.join(OUTPUT_DIR, "validation_log.csv")
AUDIT_LOG        = os.path.join(OUTPUT_DIR, "audit_log.json")

def _key_ok(k): return bool(k and len(k) > 10)

print("Config loaded.")
print(f"   Groq    : {'SET' if _key_ok(GROQ_API_KEY) else 'NOT SET'}")
print(f"   SerpApi : {'SET' if _key_ok(SERPAPI_KEY) else 'NOT SET'}")
print(f"   Apify   : {'SET' if _key_ok(APIFY_API_TOKEN) else 'NOT SET'}")

# ═══════════════════════════════════════════════════════════════════════════
# CELL 3: Shared Utilities
# ═══════════════════════════════════════════════════════════════════════════

import random, time, json, re, csv
import pandas as pd
from datetime import datetime
from rapidfuzz import fuzz

def _delay(lo=0.3, hi=0.8):
    time.sleep(random.uniform(lo, hi))

# ═══════════════════════════════════════════════════════════════════════════
# CELL 4: StateManager — Checkpoint, Resume, Logging
# ═══════════════════════════════════════════════════════════════════════════

class StateManager:
    """File-based state. Survives crashes. Appends after every entity."""

    def __init__(self):
        self.completed     = set()
        self.audit_entries = []
        self._load()

    def _load(self):
        if os.path.exists(CHECKPOINT_FILE):
            try:
                df = pd.read_csv(CHECKPOINT_FILE)
                self.completed = set(df['canonical_entity'].dropna().tolist())
                print(f"   StateManager: {len(self.completed)} entities done")
            except Exception:
                self.completed = set()
        if os.path.exists(AUDIT_LOG):
            try:
                with open(AUDIT_LOG) as f:
                    self.audit_entries = json.load(f)
            except Exception:
                self.audit_entries = []

    def is_done(self, entity): return entity in self.completed

    def work_queue(self, entity_list):
        q = [e for e in entity_list if e not in self.completed]
        print(f"   Work queue: {len(q)} remaining / {len(entity_list)} total")
        return q

    def save_entity(self, row: dict):
        exists = os.path.exists(CHECKPOINT_FILE)
        with open(CHECKPOINT_FILE, 'a', newline='', encoding='utf-8-sig') as f:
            w = csv.DictWriter(f, fieldnames=row.keys(), quoting=csv.QUOTE_ALL)
            if not exists: w.writeheader()
            w.writerow(row)
        self.completed.add(row.get('canonical_entity', ''))

    def log_validation(self, entry: dict):
        exists = os.path.exists(VALIDATION_LOG)
        with open(VALIDATION_LOG, 'a', newline='', encoding='utf-8-sig') as f:
            w = csv.DictWriter(f, fieldnames=entry.keys(), quoting=csv.QUOTE_ALL)
            if not exists: w.writeheader()
            w.writerow(entry)

    def log_audit(self, entry: dict):
        self.audit_entries.append(entry)
        with open(AUDIT_LOG, 'w', encoding='utf-8') as f:
            json.dump(self.audit_entries, f, indent=2, ensure_ascii=False, default=str)

    def reset(self):
        for f in [CHECKPOINT_FILE, VALIDATION_LOG, AUDIT_LOG]:
            if os.path.exists(f): os.remove(f)
        self.completed = set()
        self.audit_entries = []
        print("   StateManager: reset complete")

print("StateManager defined.")

# ═══════════════════════════════════════════════════════════════════════════
# CELL 5: LLM — Groq Only (reliable, JSON-aware)
# ═══════════════════════════════════════════════════════════════════════════

import requests as req

def call_groq(prompt: str, system: str = "", max_retries: int = 3) -> str:
    """Single LLM endpoint. Returns raw text."""
    if not _key_ok(GROQ_API_KEY): return ""

    messages = []
    if system: messages.append({"role": "system", "content": system})
    messages.append({"role": "user", "content": prompt})

    for attempt in range(max_retries):
        try:
            r = req.post(
                "https://api.groq.com/openai/v1/chat/completions",
                headers={"Authorization": f"Bearer {GROQ_API_KEY}",
                         "Content-Type": "application/json"},
                json={"model": GROQ_MODEL, "messages": messages,
                      "max_tokens": 600, "temperature": 0.1},
                timeout=30,
            )
            if r.status_code == 429:
                time.sleep((2 ** attempt) * 3); continue
            if r.status_code >= 500:
                if attempt < max_retries - 1: time.sleep(5); continue
                return ""
            if r.status_code != 200: return ""
            return r.json()["choices"][0]["message"]["content"]
        except req.exceptions.Timeout:
            if attempt < max_retries - 1: time.sleep(3); continue
        except Exception as e:
            print(f"     Groq error: {e}"); return ""
    return ""


def _parse_json(text: str) -> dict:
    text = re.sub(r"```(?:json)?\s*", "", text).strip()
    text = re.sub(r",\s*([}\]])", r"\1", text)
    try: return json.loads(text)
    except json.JSONDecodeError: pass
    m = re.search(r"\{.*\}", text, re.DOTALL)
    if m:
        try: return json.loads(m.group())
        except json.JSONDecodeError: pass
    return {}


def call_groq_json(prompt: str, system: str = "") -> dict:
    raw = call_groq(prompt, system)
    if not raw: return {}
    parsed = _parse_json(raw)
    if parsed: return parsed
    # Retry with stricter instruction
    raw = call_groq(prompt + "\n\nRespnd ONLY valid JSON. No markdown, no explanation.", system)
    return _parse_json(raw) if raw else {}

print("LLM wrapper defined (Groq only).")

def scrape_serpapi(entity: str, location: str = "Tunisia") -> dict:
    """SerpApi Google Maps. Returns structured venue data."""
    result = {
        "gm_name": None, "gm_rating": None, "gm_review_count": None,
        "gm_address": None, "gm_phone": None, "gm_website": None,
        "gm_category": None, "status": "no_results",
    }
    if not _key_ok(SERPAPI_KEY):
        result["status"] = "no_key"; return result

    try:
        from serpapi import GoogleSearch
        params = {
            "engine": "google_maps",
            "q": f"{entity} restaurant {location}",
            "type": "search",
            "api_key": SERPAPI_KEY,
        }
        search = GoogleSearch(params)
        data = search.get_dict()

        places = data.get("local_results", [])

        # SerpApi sometimes returns a single place instead of a list
        if not places:
            single = data.get("place_results")
            if single:
                places = [single]

        if not places:
            # Retry without "restaurant" keyword
            params["q"] = f"{entity} {location}"
            search = GoogleSearch(params)
            data = search.get_dict()
            places = data.get("local_results", [])
            if not places:
                single = data.get("place_results")
                if single:
                    places = [single]

        if not places:
            print("     SerpApi: no results"); return result

        p = places[0]

        result["gm_name"]         = p.get("title")
        result["gm_rating"]       = p.get("rating")
        result["gm_review_count"] = p.get("reviews")
        result["gm_address"]      = p.get("address")
        result["gm_phone"]        = p.get("phone")
        result["gm_website"]      = p.get("website")

        # Category — handle both str and dict types
        types_raw = p.get("types", [])
        if types_raw and isinstance(types_raw[0], dict):
            result["gm_category"] = ", ".join(t.get("name", "") for t in types_raw)[:80]
        elif types_raw and isinstance(types_raw[0], str):
            result["gm_category"] = ", ".join(types_raw)[:80]
        else:
            result["gm_category"] = p.get("type", "")

        result["status"] = "success"

        print(f"     ✓ Found: {result['gm_name']}")
        print(f"       Rating   : {result['gm_rating']} ({result['gm_review_count']} reviews)")
        print(f"       Category : {result['gm_category']}")
        print(f"       Address  : {result['gm_address']}")
        print(f"       Phone    : {result['gm_phone'] or '(none)'}")
        print(f"       Website  : {result['gm_website'] or '(none)'}")

    except Exception as e:
        print(f"     SerpApi error: {e}")
        result["status"] = f"error: {str(e)[:80]}"

    _delay()
    return result

print("SerpApi defined.")

# ═══════════════════════════════════════════════════════════════════════════
# CELL 7: Website Social Link Extractor (replaces Selenium)
# ═══════════════════════════════════════════════════════════════════════════

def extract_social_from_website(website_url: str) -> dict:
    """Fetch website HTML, extract IG/FB links. No browser needed."""
    socials = {"website_ig": None, "website_fb": None}
    if not website_url: return socials

    try:
        import httpx
        r = httpx.get(website_url, timeout=10, follow_redirects=True,
                      headers={"User-Agent": "Mozilla/5.0"})
        html = r.text

        ig = re.search(r'href=["\']?https?://(?:www\.)?instagram\.com/([A-Za-z0-9_.]{3,30})', html)
        fb = re.search(r'href=["\']?https?://(?:www\.)?facebook\.com/([A-Za-z0-9_.]{3,50})', html)

        if ig: socials["website_ig"] = ig.group(1).lower()
        if fb: socials["website_fb"] = fb.group(1).lower()

        found = []
        if socials["website_ig"]: found.append(f"IG=@{socials['website_ig']}")
        if socials["website_fb"]: found.append(f"FB=@{socials['website_fb']}")
        if found:
            print(f"     ✓ Website socials: {', '.join(found)}")
        else:
            print("     Website: no social links found")

    except Exception as e:
        print(f"     Website fetch error: {str(e)[:60]}")

    return socials

print("Website social extractor defined.")

# ═══════════════════════════════════════════════════════════════════════════
# CELL 8: Wikipedia — Existence Check
# ═══════════════════════════════════════════════════════════════════════════

def scrape_wikipedia(entity: str) -> bool:
    """Returns True if entity has a Wikipedia page (en or fr)."""
    try:
        import wikipediaapi
        for lang in ["en", "fr"]:
            wiki = wikipediaapi.Wikipedia(user_agent="Agent2-GEO/1.0", language=lang)
            for title in [entity, entity.title(), entity.replace(" ", "_")]:
                if wiki.page(title).exists():
                    print(f"     ✓ Wikipedia ({lang})")
                    return True
        print("     Wikipedia: not found")
    except Exception as e:
        print(f"     Wikipedia error: {e}")
    return False

print("Wikipedia defined.")

def scrape_tripadvisor(entity: str) -> dict:
    """DDG snippet parse for TA rating + review count. LLM extracts data."""
    result = {"ta_rating": None, "ta_review_count": None, "ta_url": None}

    _delay(1.5, 2.5)

    try:
        from ddgs import DDGS
        query = f"{entity} restaurant tripadvisor Tunisia"
        with DDGS() as ddgs:
            hits = list(ddgs.text(query, max_results=8))

        # Collect all TA snippets
        ta_snippets = []
        for hit in hits:
            if "tripadvisor.com" not in hit.get("href", ""):
                continue
            if not result["ta_url"]:
                result["ta_url"] = hit["href"]
            snippet = hit.get("body", "")
            title = hit.get("title", "")
            if snippet:
                ta_snippets.append(f"{title} — {snippet}")

        if not ta_snippets:
            print("     TripAdvisor: no snippets found")
            return result

        # LLM extracts rating + review count from snippets
        combined = "\n".join(ta_snippets[:3])
        parsed = call_groq_json(
            f'Extract TripAdvisor rating and review count from these search snippets '
            f'for the restaurant "{entity}":\n\n{combined}\n\n'
            f'Respond ONLY JSON: {{"ta_rating": <float or null>, "ta_review_count": <int or null>}}\n'
            f'If you cannot find a rating or count, use null.'
        )

        if parsed.get("ta_rating") is not None:
            result["ta_rating"] = float(parsed["ta_rating"])
            print(f"     ✓ TA rating: {result['ta_rating']}")
        if parsed.get("ta_review_count") is not None:
            result["ta_review_count"] = int(parsed["ta_review_count"])
            print(f"     ✓ TA reviews: {result['ta_review_count']}")

        if not result["ta_rating"] and not result["ta_review_count"]:
            print("     TripAdvisor: LLM could not extract data from snippets")

    except Exception as e:
        print(f"     TripAdvisor error: {e}")

    return result

# ═══════════════════════════════════════════════════════════════════════════
# CELL 10: Handle Resolution — Priority: Website → DDG → None
# ═══════════════════════════════════════════════════════════════════════════

def resolve_ig_handle(entity: str, website_ig: str) -> tuple:
    """Returns (handle, source). Website first, DDG fallback."""
    if website_ig:
        return website_ig, "website"

    # DDG fallback
    try:
        from ddgs import DDGS
        _delay(1, 2)
        with DDGS() as ddgs:
            hits = list(ddgs.text(f'"{entity}" site:instagram.com', max_results=5))
        for hit in hits:
            m = re.search(r"instagram\.com/([a-zA-Z0-9_.]{3,30})/?", hit.get("href", ""))
            if m:
                handle = m.group(1).lower()
                return handle, "ddg"
    except Exception:
        pass
    return None, "none"


def resolve_fb_handle(entity: str, website_fb: str) -> tuple:
    """Returns (handle, source). Website first, DDG fallback."""
    if website_fb:
        return website_fb, "website"

    try:
        from ddgs import DDGS
        _delay(1, 2)
        with DDGS() as ddgs:
            hits = list(ddgs.text(f'"{entity}" site:facebook.com', max_results=5))
        for hit in hits:
            m = re.search(r"facebook\.com/([A-Za-z0-9_.]{3,50})/?", hit.get("href", ""))
            if m:
                handle = m.group(1).lower()
                return handle, "ddg"
    except Exception:
        pass
    return None, "none"

print("Handle resolution defined.")

# ═══════════════════════════════════════════════════════════════════════════
# CELL 11: LLM Validation — The Agent's Decision Layer
# ═══════════════════════════════════════════════════════════════════════════

def validate_is_restaurant(entity: str) -> dict:
    """Pre-scrape: Is this entity plausibly a restaurant?"""
    result = call_groq_json(
        f'The entity "{entity}" was recommended by LLMs when asked about '
        f'Tunisian restaurants. Based on the name alone, is this plausibly '
        f'a restaurant, café, or food business?\n'
        f'When uncertain, answer true.\n'
        f'Respond ONLY JSON: {{"is_restaurant": true/false, "reason": "brief"}}'
    )
    return result if result else {"is_restaurant": True, "reason": "LLM unavailable"}


def validate_category(entity: str, category: str, address: str) -> dict:
    """Post-SerpApi: Confirm entity is a restaurant using Google Maps data."""
    result = call_groq_json(
        f'Entity: "{entity}"\n'
        f'Google Maps category: "{category}"\n'
        f'Google Maps address: "{address}"\n\n'
        f'Is this a restaurant, café, bar, or food business?\n'
        f'Respond ONLY JSON: {{"is_restaurant": true/false, "reason": "brief"}}'
    )
    return result if result else {"is_restaurant": True, "reason": "LLM unavailable"}


def validate_handle(entity: str, handle: str, platform: str) -> dict:
    """Pre-Apify gate: Does this handle belong to this brand?"""
    result = call_groq_json(
        f'Brand: "{entity}" (Tunisian restaurant)\n'
        f'Resolved {platform} handle: "@{handle}"\n\n'
        f'Does this {platform} account plausibly belong to this restaurant?\n'
        f'Consider: handle contains brand name → likely YES, '
        f'generic word or person name unrelated → likely NO.\n'
        f'Respond ONLY JSON: {{"plausible": true/false, "reason": "brief"}}'
    )
    return result if result else {"plausible": True, "reason": "LLM unavailable"}


def validate_data_quality(entity: str, data: dict) -> dict:
    """Post-scrape: Check consistency of all scraped data."""
    prompt = (
        f'You are a data quality auditor for Tunisian restaurant data.\n'
        f'Brand: "{entity}"\n'
        f'Google Maps: {data.get("gm_rating")} stars, {data.get("gm_review_count")} reviews\n'
        f'Address: {data.get("gm_address") or "NOT SCRAPED"}\n'
        f'Phone: {data.get("gm_phone") or "NOT SCRAPED"}\n'
        f'Website: {data.get("gm_website") or "NOT SCRAPED"}\n'
        f'TripAdvisor: {data.get("ta_rating")} stars\n'
        f'Instagram: @{data.get("ig_handle") or "NOT FOUND"} | {data.get("ig_followers", 0)} followers\n'
        f'Facebook: @{data.get("fb_handle") or "NOT FOUND"} | {data.get("fb_page_likes", 0)} likes\n\n'
        f'Check for inconsistencies, implausible values, or wrong entities.\n'
        f'Respond ONLY JSON:\n'
        f'{{"issues": [{{"field": "name", "severity": "invalid|conflict|implausible", "reason": "brief"}}], '
        f'"confidence": 0.0-1.0, "summary": "brief"}}\n'
        f'If no issues: {{"issues": [], "confidence": 1.0, "summary": "All consistent."}}'
    )
    result = call_groq_json(prompt)
    return result if result else {"issues": [], "confidence": 0.8, "summary": "LLM unavailable"}

print("LLM validation layer defined.")

# ═══════════════════════════════════════════════════════════════════════════
# CELL 12: Apify Scrapers — IG + FB (no Instaloader)
# ═══════════════════════════════════════════════════════════════════════════

def scrape_instagram_apify(handle: str) -> dict:
    """Apify Instagram profile. Primary and only IG scraper."""
    result = {"ig_followers": 0, "ig_posts": 0, "ig_engagement_rate": 0.0,
              "ig_bio": "", "ig_scraper": "none"}
    if not handle or not _key_ok(APIFY_API_TOKEN): return result

    try:
        from apify_client import ApifyClient
        client = ApifyClient(APIFY_API_TOKEN)
        print(f"     Apify IG: @{handle}...")

        run = client.actor("apify/instagram-profile-scraper").call(
            run_input={"usernames": [handle], "resultsLimit": 1},
            timeout_secs=300,
        )
        items = list(client.dataset(run["defaultDatasetId"]).iterate_items())
        if items:
            r = items[0]
            result["ig_followers"]       = r.get("followersCount", 0)
            result["ig_posts"]           = r.get("postsCount", 0)
            result["ig_engagement_rate"] = r.get("engagementRate", 0.0)
            result["ig_bio"]             = (r.get("biography") or "")[:200]
            result["ig_scraper"]         = "apify"
            print(f"     ✓ {result['ig_followers']:,} followers | {result['ig_posts']} posts")
        else:
            print(f"     Apify IG: no data for @{handle}")
    except Exception as e:
        print(f"     Apify IG error: {e}")

    _delay()
    return result


def scrape_facebook_apify(handle: str) -> dict:
    """Apify Facebook Pages. Fixed: resultsLimit instead of maxPosts."""
    result = {"fb_page_likes": 0, "fb_post_engagement": 0.0, "fb_scraper": "none"}
    if not handle or not _key_ok(APIFY_API_TOKEN): return result

    try:
        from apify_client import ApifyClient
        client = ApifyClient(APIFY_API_TOKEN)
        print(f"     Apify FB: @{handle}...")

        run = client.actor("apify/facebook-pages-scraper").call(
            run_input={
                "startUrls": [{"url": f"https://www.facebook.com/{handle}"}],
                "resultsLimit": 10,       # FIXED: was maxPosts (deprecated)
                "maxPostComments": 0,
                "maxReviews": 0,
            },
            timeout_secs=180,
        )
        items = list(client.dataset(run["defaultDatasetId"]).iterate_items())
        if items:
            page = items[0]
            result["fb_page_likes"] = page.get("likes", 0) or 0
            posts = page.get("posts", []) or []
            if posts:
                total = sum(
                    (p.get("likes", 0) or 0) + (p.get("comments", 0) or 0) +
                    (p.get("shares", 0) or 0) for p in posts
                )
                result["fb_post_engagement"] = round(total / len(posts), 1)
            result["fb_scraper"] = "apify"
            print(f"     ✓ {result['fb_page_likes']:,} likes | {result['fb_post_engagement']} avg eng")
        else:
            print(f"     Apify FB: no data for @{handle}")
    except Exception as e:
        print(f"     Apify FB error: {e}")

    _delay()
    return result

print("Apify scrapers defined (IG + FB, no Instaloader).")

# ═══════════════════════════════════════════════════════════════════════════
# CELL 13: Derived Features (deterministic, no LLM)
# ═══════════════════════════════════════════════════════════════════════════

def compute_derived(row: dict) -> dict:
    hw = bool(row.get("gm_website"))
    hp = bool(row.get("gm_phone"))
    ha = bool(row.get("gm_address"))
    hi = bool(row.get("ig_handle"))
    hf = bool(row.get("fb_handle"))
    ht = bool(row.get("ta_url"))
    hwk = bool(row.get("has_wikipedia"))

    entity = (row.get("canonical_entity") or "").lower()
    bio    = (row.get("ig_bio") or "").lower()
    bio_match = fuzz.partial_ratio(entity, bio) > 60 if entity and bio else False

    return {
        "has_website":           hw,
        "has_phone":             hp,
        "has_address":           ha,
        "has_instagram":         hi,
        "has_facebook":          hf,
        "has_tripadvisor":       ht,
        "has_wikipedia":         hwk,
        "data_source_count":     sum([hw, hp, hi, hf, ht, hwk]),
        "review_total":          (row.get("gm_review_count") or 0) + (row.get("ta_review_count") or 0),
        "ig_bio_mentions_brand": bio_match,
    }

print("Derived features defined.")

# ═══════════════════════════════════════════════════════════════════════════
# CELL 14: Orchestrator — Full Pipeline Per Entity
# ═══════════════════════════════════════════════════════════════════════════

def process_entity(entity: str, state: StateManager) -> dict:
    """Agentic pipeline for one entity. LLM decides at every gate."""

    start = datetime.now()
    audit = {"canonical_entity": entity, "steps": {}, "llm_calls": 0, "api_calls": 0}
    row = {"canonical_entity": entity}

    print(f"\n{'─'*60}")
    print(f"  {entity.upper()}")
    print(f"{'─'*60}")

    # ── GATE 1: Pre-scrape scope validation (LLM) ────────────────────
    print("  ► Pre-scrape validation")
    val = validate_is_restaurant(entity)
    audit["llm_calls"] += 1
    row["is_restaurant"] = val.get("is_restaurant", True)
    state.log_validation({"canonical_entity": entity, "step": "pre_scrape",
                          "decision": row["is_restaurant"], "reason": val.get("reason", "")})

    if not row["is_restaurant"]:
        print(f"     ✗ Out of scope: {val.get('reason')}")
        row.update({k: None for k in [
            "gm_rating", "gm_review_count", "gm_address", "gm_phone",
            "gm_website", "gm_category", "ta_rating", "ta_review_count",
            "ta_url", "ig_handle", "ig_followers", "ig_posts",
            "ig_engagement_rate", "ig_bio", "fb_handle", "fb_page_likes",
            "fb_post_engagement", "has_wikipedia",
        ]})
        row.update(compute_derived(row))
        row["overall_confidence"] = 0.0
        row["scrape_timestamp"] = datetime.now().isoformat()
        state.save_entity(row)
        audit["duration_s"] = (datetime.now() - start).total_seconds()
        state.log_audit(audit)
        return row

    # ── STEP 1: Google Maps (SerpApi) ─────────────────────────────────
    print("  ► Google Maps (SerpApi)")
    gm = scrape_serpapi(entity)
    audit["api_calls"] += 1
    audit["steps"]["serpapi"] = gm["status"]

    row["gm_rating"]       = gm["gm_rating"]
    row["gm_review_count"] = gm["gm_review_count"]
    row["gm_address"]      = gm["gm_address"]
    row["gm_phone"]        = gm["gm_phone"]
    row["gm_website"]      = gm["gm_website"]
    row["gm_category"]     = gm["gm_category"]

    # ── GATE 2: Category validation (LLM) ─────────────────────────────
    if gm["gm_category"] and gm["status"] == "success":
        print("  ► Category validation")
        cat_val = validate_category(entity, str(gm["gm_category"]), str(gm["gm_address"]))
        audit["llm_calls"] += 1

        if not cat_val.get("is_restaurant", True):
            print(f"     ✗ Not a restaurant: {cat_val.get('reason')}")
            row["is_restaurant"] = False
            state.log_validation({"canonical_entity": entity, "step": "category",
                                  "decision": False, "reason": cat_val.get("reason", "")})
            # Save Google Maps data but skip social scraping
            row.update({k: None for k in [
                "ta_rating", "ta_review_count", "ta_url",
                "ig_handle", "ig_followers", "ig_posts",
                "ig_engagement_rate", "ig_bio",
                "fb_handle", "fb_page_likes", "fb_post_engagement",
                "has_wikipedia",
            ]})
            row.update(compute_derived(row))
            row["overall_confidence"] = 0.0
            row["scrape_timestamp"] = datetime.now().isoformat()
            state.save_entity(row)
            audit["duration_s"] = (datetime.now() - start).total_seconds()
            state.log_audit(audit)
            return row

    # ── STEP 2: Wikipedia ─────────────────────────────────────────────
    print("  ► Wikipedia")
    row["has_wikipedia"] = scrape_wikipedia(entity)

    # ── STEP 3: TripAdvisor ───────────────────────────────────────────
    print("  ► TripAdvisor")
    ta = scrape_tripadvisor(entity)
    row["ta_rating"]       = ta["ta_rating"]
    row["ta_review_count"] = ta["ta_review_count"]
    row["ta_url"]          = ta["ta_url"]

    # ── STEP 4: Website social link extraction ────────────────────────
    website_socials = {"website_ig": None, "website_fb": None}
    if gm["gm_website"]:
        print("  ► Website social links")
        website_socials = extract_social_from_website(gm["gm_website"])

    # ── STEP 5a: Instagram ────────────────────────────────────────────
    print("  ► Instagram")
    ig_handle, ig_source = resolve_ig_handle(entity, website_socials["website_ig"])
    ig_validated = False

    if ig_handle:
        print(f"     Handle: @{ig_handle} (source: {ig_source})")
        # LLM gate — validate before spending Apify credits
        hval = validate_handle(entity, ig_handle, "Instagram")
        audit["llm_calls"] += 1

        if not hval.get("plausible", True):
            print(f"     ✗ Rejected: {hval.get('reason')}")
            state.log_validation({"canonical_entity": entity, "step": "ig_handle",
                                  "decision": False, "reason": hval.get("reason", ""),
                                  "handle": ig_handle, "source": ig_source})
            ig_handle = None
            ig_source = "rejected"
        else:
            ig_validated = True
            print(f"     ✓ Handle validated")

    ig_data = scrape_instagram_apify(ig_handle) if ig_handle else {
        "ig_followers": 0, "ig_posts": 0, "ig_engagement_rate": 0.0,
        "ig_bio": "", "ig_scraper": "none",
    }
    if ig_handle: audit["api_calls"] += 1

    row["ig_handle"]          = ig_handle
    row["ig_handle_source"]   = ig_source
    row["ig_followers"]       = ig_data["ig_followers"]
    row["ig_posts"]           = ig_data["ig_posts"]
    row["ig_engagement_rate"] = ig_data["ig_engagement_rate"]
    row["ig_bio"]             = ig_data.get("ig_bio", "")

    # ── STEP 5b: Facebook ─────────────────────────────────────────────
    print("  ► Facebook")
    fb_handle, fb_source = resolve_fb_handle(entity, website_socials["website_fb"])
    fb_validated = False

    if fb_handle:
        print(f"     Handle: @{fb_handle} (source: {fb_source})")
        hval = validate_handle(entity, fb_handle, "Facebook")
        audit["llm_calls"] += 1

        if not hval.get("plausible", True):
            print(f"     ✗ Rejected: {hval.get('reason')}")
            state.log_validation({"canonical_entity": entity, "step": "fb_handle",
                                  "decision": False, "reason": hval.get("reason", ""),
                                  "handle": fb_handle, "source": fb_source})
            fb_handle = None
            fb_source = "rejected"
        else:
            fb_validated = True
            print(f"     ✓ Handle validated")

    fb_data = scrape_facebook_apify(fb_handle) if fb_handle else {
        "fb_page_likes": 0, "fb_post_engagement": 0.0, "fb_scraper": "none",
    }
    if fb_handle: audit["api_calls"] += 1

    row["fb_handle"]          = fb_handle
    row["fb_handle_source"]   = fb_source
    row["fb_page_likes"]      = fb_data["fb_page_likes"]
    row["fb_post_engagement"] = fb_data["fb_post_engagement"]

    # ── STEP 6: Data quality validation (LLM) ─────────────────────────
    print("  ► Data quality check")
    quality = validate_data_quality(entity, row)
    audit["llm_calls"] += 1
    n_issues = len(quality.get("issues", []))
    llm_conf = quality.get("confidence", 0.8)
    print(f"     Issues: {n_issues} | LLM confidence: {llm_conf}")
    if quality.get("summary"):
        print(f"     {quality['summary']}")

    # ── STEP 7: Derived features + confidence ─────────────────────────
    row.update(compute_derived(row))

    # Deterministic confidence: blend field completeness with LLM assessment
    field_score = row["data_source_count"] / 6.0  # max 6 sources
    row["overall_confidence"] = round(0.6 * field_score + 0.4 * llm_conf, 3)
    row["validation_flags"]   = n_issues
    row["scrape_timestamp"]   = datetime.now().isoformat()

    # ── SAVE (checkpoint) ─────────────────────────────────────────────
    state.save_entity(row)

    duration = (datetime.now() - start).total_seconds()
    audit["duration_s"]  = duration
    audit["confidence"]  = row["overall_confidence"]
    audit["flags"]       = n_issues
    state.log_audit(audit)

    print(f" Done ({duration:.0f}s) | conf={row['overall_confidence']} "
          f"| sources={row['data_source_count']} | flags={n_issues}")

    return row

print("Orchestrator defined.")

"""
═══════════════════════════════════════════════════════════════════════════════
Agent 2 — Web Feature Collector (Agentic)
═══════════════════════════════════════════════════════════════════════════════
GEO Pipeline: Agent 1 (LLM features) → Agent 2 (web features) → Agent 3

Tools:
  SerpApi        — Google Maps data (rating, reviews, address, phone, website)
  httpx          — Website social link extraction (IG/FB from business website)
  DDG            — TripAdvisor URLs + fallback handle resolution
  Wikipedia API  — Existence check (binary feature)
  Apify IG       — Instagram profile data (primary, no Instaloader)
  Apify FB       — Facebook page data (fixed resultsLimit)
  Groq           — All LLM calls (validation, hallucination check)

Removed:
  Instaloader    — 100% failure rate (IG blocks anonymous access)
  Selenium       — Replaced by SerpApi + httpx website fetch
  OpenRouter     — 100% failure rate on free tier
  ReflectionEngine — Output not needed for feature table

Agentic principles:
  - LLM validates scope, handles, and data quality (no hardcoded blacklists)
  - Checkpoint after every entity (crash recovery)
  - LLM gate before Apify (don't spend credits on wrong handles)
  - Every decision logged with reasoning
═══════════════════════════════════════════════════════════════════════════════
"""

# ═══════════════════════════════════════════════════════════════════════════
# CELL 15: Main Entry Point
# ═══════════════════════════════════════════════════════════════════════════

def run_agent2(entity_list: list, fresh_start: bool = False, delay: int = 5):
    """
    Main entry. Pass entity list, get web_features.csv.
    Resumes from checkpoint on crash. Set fresh_start=True to reset.
    """
    state = StateManager()
    if fresh_start:
        state.reset()
        state = StateManager()

    queue = state.work_queue(entity_list)

    print(f"\n{'='*60}")
    print(f"  Agent 2 — Web Feature Collector")
    print(f"  Entities : {len(queue)} remaining / {len(entity_list)} total")
    print(f"  Tools    : SerpApi → Website → DDG → Wikipedia → Apify(IG/FB)")
    print(f"  LLM      : Groq ({GROQ_MODEL})")
    print(f"  Output   : {CHECKPOINT_FILE}")
    print(f"{'='*60}")

    for i, entity in enumerate(queue):
        if i > 0:
            print(f"\n  ⏳ {delay}s cooldown...")
            time.sleep(delay)

        try:
            process_entity(entity, state)
        except Exception as e:
            print(f"\n  ❌ ERROR on '{entity}': {e}")
            state.save_entity({
                "canonical_entity": entity,
                "is_restaurant": None,
                "overall_confidence": 0.0,
                "scrape_timestamp": datetime.now().isoformat(),
            })

    # Summary
    print(f"\n{'='*60}")
    print(f"  Agent 2 Complete")
    if os.path.exists(CHECKPOINT_FILE):
        df = pd.read_csv(CHECKPOINT_FILE)
        in_scope = df[df['is_restaurant'] == True] if 'is_restaurant' in df.columns else df
        print(f"  Total      : {len(df)}")
        print(f"  In scope   : {len(in_scope)}")
        print(f"  Out scope  : {len(df) - len(in_scope)}")
    print(f"  Output     : {CHECKPOINT_FILE}")
    print(f"  Audit      : {AUDIT_LOG}")
    print(f"  Decisions  : {VALIDATION_LOG}")
    print(f"{'='*60}")


# ── LangGraph node ────────────────────────────────────────────────────────────

from pipeline_state import PipelineState


def run_agent2_node(state: PipelineState) -> PipelineState:
    """LangGraph node: runs Agent 2 web enrichment and merges results into state."""
    errors = list(state.get("errors", []))

    # Build entity list from the global features computed by Agent 1.
    global_features = state.get("entity_features_global") or []
    entity_list = [r["canonical_entity"] for r in global_features if r.get("canonical_entity")]

    if not entity_list:
        errors.append("agent2: entity_features_global is empty — skipping web enrichment")
        return {**state, "errors": errors, "current_step": "agent2_skipped"}

    try:
        run_agent2(entity_list, fresh_start=False)
    except Exception as exc:
        errors.append(f"agent2: {exc}")
        return {**state, "errors": errors, "current_step": "agent2_error"}

    # Read the checkpoint CSV back and store as serialisable records.
    web_features: list = []
    try:
        import pandas as pd
        if os.path.exists(CHECKPOINT_FILE):
            web_features = pd.read_csv(CHECKPOINT_FILE, encoding="utf-8-sig").to_dict(orient="records")
    except Exception as exc:
        errors.append(f"agent2: could not read checkpoint CSV: {exc}")

    return {
        **state,
        "web_features": web_features,
        "errors":       errors,
        "current_step": "agent2",
    }